#!/usr/bin/env bash

[[ " help ansible-playbook:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in

  help | ansible-playbook:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return ansible-playbook plugin help content"
      cat<<help_content
    ansible-playbook:vault-pass, Insert new vault password for encrypt/decrypt of passwords
help_content
    }

    if [[ $1 = "ansible-playbook:help" ]]; then
      echo -e 'Usage: dokku ansible-playbook:COMMAND'
      echo ''
      echo 'Run ansible playbooks during deployment'
      echo ''
      echo 'Commands:'
      help_content_func | sort | column -c2 -t -s,
    elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
      help_content_func
    else
      cat<<help_desc
    ansible-playbook, Run ansible playbooks during deployment
help_desc
    fi
    ;;

  vault-pass)
    dokku-ansible-playbook-vault-pass-cmd "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac
