#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

export DEBIAN_FRONTEND=noninteractive

if ! command -v "ansible" &>/dev/null; then
  echo "-----> installing ansible"
  apt install --allow -qq -y ansible
fi
