#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

dokku-ansible-playbook-dependencies() {
  export DEBIAN_FRONTEND=noninteractive

  if ! command -v "ansible" &>/dev/null; then
    dokku_col_log_info1_quiet "installing ansible"
    apt install -qq -y ansible
  fi
}

dokku-ansible-playbook-dependencies "$@"
