#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
PLAYBOOK="$DOKKU_ROOT/$APP/ansible/post-deploy.yml"
REQUIREMENTS="$DOKKU_ROOT/$APP/ansible/requirements.yml"

echo "-----> Running post-deploy ansible playbook"
. $(dirname "$0")/functions
run_playbook "$PLAYBOOK" "$REQUIREMENTS"
