#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLAYBBOOK=".ansible/pre-deploy.yml"

echo "-----> Running pre-deploy ansible playbook"
. $(dirname "$0")/functions
run_playbook "$PLAYBOOK"
