#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

dokku-ansible-playbook-pre-deploy() {
  declare APP="$1"
  declare PLAYBOOK="$DOKKU_LIB_ROOT/data/ansible/$APP/pre-deploy.yml"
  declare REQUIREMENTS="$DOKKU_LIB_ROOT/data/ansible/$APP/requirements.yml"

  . $(dirname "$0")/functions

  dokku_col_log_info1_quiet "Running pre-deploy ansible playbook"

  run_playbook "$PLAYBOOK" "$REQUIREMENTS"
}

dokku-ansible-playbook-pre-deploy "$@"
