#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-ansible-default() {
  declare desc="Run ansible playbooks during deployment"
  local cmd="ansible"
  dokku_log_fail "Missing command, please run 'dokku ansible:help'"
}

cmd-ansible-default "$@"
